"""add cpf to customer

Revision ID: 5aa4e96ded62
Revises: 8b9751a017a4
Create Date: 2026-04-12 15:30:06.362531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa4e96ded62'
down_revision = '8b9751a017a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('cpf')

    # ### end Alembic commands ###
