"""adiciona campo type em service_images

Revision ID: 71dd821eb81c
Revises: d9f0c877367c
Create Date: 2026-03-21 22:37:24.034412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dd821eb81c'
down_revision = 'd9f0c877367c'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("service_images", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type",
                sa.String(length=20),
                nullable=True
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_images', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
